### ISSUE TITLE
Ideation: Releases page (used to be called What's new page)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/digital-design-ideation#140]
#### Objective:

Provide IBM.com Library adopters insight into what is new and upcoming IBM.com Library offers.

#### Example

https://material.io/whats-new

![Screenshot_2020-09-04 Material Design.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/ae8ff3f9-9c74-40f9-bcac-e7358f8652b5)

**Comment by JennySanchez** [comment]
This will be the 2021 focus.

**Comment by JennySanchez** [comment]
Need to work with a developer on creating this page and automate the process. 
FYI: @jeffchew

**Comment by tamcai-ibm** [comment]
Hi, I was directed here to suggest a new feature for IDL/Carbon/DDS updates. Since I'm on the UMX team, I do not regularly receive updates on upcoming or WIP designs / patterns / new / changes to existing components. For example, I presented a design a few days ago on DDS Partner Review session and didn't know there were some new changes in how the hero images could be resized...previously, I thought it was restricted to only 16:9 ratio. Or another instance where Carbon Expressive does not yet have a "horizontal container tab UI" but it's present in the Carbon product kit. I was notified it's on the to-do list to have implemented. Having an update on this would be nice.

Is there an email newsletter I could subscribe to stay up todate? I know we have something kind of like Slack channels but there can be over 100+ messages (...thus buried deep) in a day on various topics. I think a dedicated email newsletter would help pinpoint things for scannability such as how Sketch or Invision does in their "What's new" email newsletters. Thank iyou.

**Comment by JennySanchez** [comment]
Thank you for the feedback, @tamcai-ibm. Your feedback help @ljcarot and I not only understand adopter needs but also spark new idea we can try to make the adoption experience better for adopters.

**Comment by JennySanchez** [comment]
https://www.carbondesignsystem.com/whats-happening/releases/

![Screenshot_2021-05-03 Releases – Carbon Design System.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/b8d60598-fa53-4dd6-a9de-0c552f79a19d)

**Comment by JennySanchez** [comment]
Will share the initial designs in the sprint demo. 

![Screen Shot 2021-06-03 at 3.26.23 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/053e652b-88d2-4d2e-b3d2-db160c9b86d5)

**Next step:** 

- We need to validate the content structure with adopters to find out what info they are looking for when it comes to release updates.
- With the findings, then we can finalize the design.

#1023 created for finalizing the design
