### ISSUE TITLE
(MVP version) Content strategy for Components section on the website

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#39]
### User story
~~As an IBM.com maker, I would like to understand how to use any specific component the right way.~~

As an IBM.com library website contributor, I need a way to set up any website page for a component, so that our adopter can see a cohesive structure across the Components section and find information intuitively and efficiently.

FYI: @oliviaflory I updated the user story originally crafted by Wonil, let me know if it works for you and if you have any questions.

### Tasks
1. Collect adopter needs and pain points around component usage (#43 )
2. Compose a list of information necessary for component guidelines
3. Identifying the essential pieces of information for MVP publishing (#20)
4. Creating a content template wireframe

### Reference
Link to [component content template](https://ibm.ent.box.com/notes/548757356232) from 2019
### Acceptance criteria
- [x] Content template wireframe is available for use in the template update story
- [x] Prioritized list of components to be published is available

**Comment by JennySanchez** [comment]
@oliviaflory As mentioned yesterday, all the material shared via the Mural boards from #43 and #20 is available for you. Please see the Acceptance criteria section above for task expectation and let me know if you have any questions.

**Comment by JennySanchez** [comment]
Hi @larahanlon2 We have the MVP template, published criteria, and priority all on the [IBM.com Library Publishing Criteria and Priority Planning Mural board](https://app.mural.co/invitation/mural/ibm14/1592586700298?sender=chsanche&key=0f7c3917-398c-4fc0-a429-ebe8667b20ad) for discussion.

Please let me know if there's anything else we need to work on for now. Otherwise, I'd like to move this task issue to the "Done" column. As we go, I'd like to continue creating series of Sketch templates based on the intents or needs so we can have a complete overview of the content structure needs by the end of 2020.

**Comment by JennySanchez** [comment]
Based on the discussion with Wonil. We are good to close this task and we will work on the next iteration of the strategy via #104
